#if defined _customwpn_json_const_included
  #endinput
#endif
#define _customwpn_json_const_included

new const JSON_IMPULSE_ID[] = "impulseid";
new const JSON_WPN_ID[] = "weaponid";
new const JSON_WPN_FAMILY[] = "weaponfamily";
new const JSON_FORCE_ROLL[] = "forceRoll";
new const JSON_CSW_ID[] = "cswid";
new const JSON_CSW_WPN_ID[] = "cswpnid";
new const JSON_DISPLAY_NAME[] = "displayName";
new const JSON_SPECIAL_ID[] = "specialId";

new const JSON_V_MODEL[] = "vModel";
new const JSON_P_MODEL[] = "pModel";
new const JSON_W_MODEL[] = "wModel";

new const JSON_AUTO_SHOOT[] = "autoShoot";
new const JSON_CLIP_RELOAD[] = "clipReload";

new const JSON_OVERRIDE_SHOOT_SOUND[] = "overrideShootSound";
new const JSON_SHOOT_SOUND_PATH[] = "shootSoundPath";
new const JSON_SHOOT_SOUND_SLICENCED_PATH[] = "shootSoundSlicencedPath";

new const JSON_COST[] = "cost";
new const JSON_CLIP_SIZE[] = "clipsize";
new const JSON_DMG_MULTIPLIER[] = "dmgMultiplier";
new const JSON_RELOAD_TIME[] = "reloadTime";
new const JSON_SHOOT_INTERVAL[] = "shootInterval";
new const JSON_MOVE_SPEED[] = "moveSpeed";
new const JSON_RECOIL_MULTIPLIER[] = "recoilMultiplier";

new const JSON_SHOOT_SEQ[] = "shootSequence";
new const JSON_SHOOT_SEQ_SPECIAL[] = "shootSequenceSpecial";
new const JSON_RELOAD_SEQ[] = "reloadSequence";
new const JSON_DRAW_SEQ[] = "drawSequence";

new const JSON_Z_DMG_MULTIPLIER[] = "zdmgMultiplier";
new const JSON_Z_TIER[] = "ztier";
new const JSON_Z_KNOCKBACK[] = "zknockback";
new const JSON_Z_SUBTYPE[] = "zsubtype";

// ============ KNIFE =============== //
/*
new const JSON_KNIFE_LEFT_DMG[] =
new const JSON_KNIFE_LEFT_DISTANCE[] =
new const JSON_KNIFE_LEFT_ANGLE[] =
new const JSON_KNIFE_RIGHT_DMG[] =
new const JSON_KNIFE_RIGHT_DISTANCE[] =
new const JSON_KNIFE_RIGHT_ANGLE[] =
*/