/* Sublime AMXX Editor v2.2 */

#if defined _zombie_scenario_const_included
	#endinput
#endif
#define _zombie_scenario_const_included

/* Load custom module ?

#pragma reqlib LIBRARY_NAME
#if !defined AMXMODX_NOAUTOLOAD
	#pragma loadlib LIBRARY_NAME
#endif

*/

#define STAGE_1 1
#define STAGE_2 2
#define STAGE_3 3
#define STAGE_4 4
#define STAGE_5	5
#define STAGE_6	6
#define STAGE_7	7

#define DO_NOT_HIDE 999
// Add your code here...
