/* Sublime AMXX Editor v2.2 */

#if defined _zombie_scenario_const_included
	#endinput
#endif
#define _zombie_scenario_const_included

new const JSON_Z_DMG_MULTIPLIER[] = "zdmgMultiplier";
new const JSON_Z_TIER[] = "ztier";
new const JSON_Z_KNOCKBACK[] = "zknockback";
new const JSON_Z_SUBTYPE[] = "zsubtype";

#define STAGE_1 1
#define STAGE_2 2
#define STAGE_3 3
#define STAGE_4 4
#define STAGE_5	5
#define STAGE_6	6
#define STAGE_7	7

#define MAX_STAGE 7
#define MAX_ZTIER 7

#define DO_NOT_HIDE 999

#define ZSubType_SUP 0
#define ZSubType_DMG 1
